### ISSUE TITLE
[BUG] Object.prototype in Node.js

### ISSUE THREAD

**Issue by ybelenko** [moment/luxon#1002]
**Describe the bug**
There is an error when you use library with Node.js. If I understand correct Node.js doesn't provide `Object.prototype`. Some polyfill or fix needed.

```console
$  node src/generateReport.js
/Library/WebServer/Documents/www/.notifier/node_modules/luxon/build/node/luxon.js:318
  return Object.prototype.hasOwnProperty.call(obj, prop);
                                         ^

TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at hasOwnProperty (/Library/WebServer/Documents/www/.notifier/node_modules/luxon/build/node/luxon.js:318:42)
    at Duration.plus (/Library/WebServer/Documents/www/.notifier/node_modules/luxon/build/node/luxon.js:3220:11)
    at arr.reduce.Duration.fromObject.seconds (/Library/WebServer/Documents/www/.notifier/src/reducers/getStatsFromArray.js:74:17)
    at Array.reduce (<anonymous>)
    at getTotalDuration (/Library/WebServer/Documents/www/.notifier/src/reducers/getStatsFromArray.js:73:14)
    at module.exports (/Library/WebServer/Documents/www/.notifier/src/reducers/getStatsFromArray.js:125:25)
    at Query.onResult (/Library/WebServer/Documents/www/.notifier/src/generateReport.js:13:17)
    at /Library/WebServer/Documents/www/.notifier/node_modules/mysql2/lib/commands/query.js:72:16
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**To Reproduce**
Cannot show the code because it's huge and I cannot find where exactly error throws. Hope that log from above is enough.

**Actual vs Expected behavior**
Package should work without errors obviously.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOs 10.14.6
- Browser [e.g. Chrome 84, safari 14.0] Node.js v14.17.1
- Luxon version [e.g. 1.25.0] ^1.28.0
- Your timezone [e.g. "America/New_York"] Seems not really important

**Comment by ybelenko** [comment]
Sorry, it wasn't a bug I passed timestamps in wrong format. Closed.
