### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by alewaros** [moment/luxon#104]
When accessing any property or function (e.g. isValid or toISO()) of a DateTime instance in a heavy promise-based environment the following error occurs:

```
RangeError: Maximum call stack size exceeded
    at DateTime.get$$1 (/Users/aj/Developer/Work/Selina/SelinaCore/node_modules/luxon/build/cjs/luxon.js:7717:25)
    at DateTime.get$$1 (/Users/aj/Developer/Work/Selina/SelinaCore/node_modules/luxon/build/cjs/luxon.js:7718:19)
    at DateTime.get$$1 (/Users/aj/Developer/Work/Selina/SelinaCore/node_modules/luxon/build/cjs/luxon.js:7718:19)
    at DateTime.get$$1 (/Users/aj/Developer/Work/Selina/SelinaCore/node_modules/luxon/build/cjs/luxon.js:7718:19)
    at DateTime.get$$1 (/Users/aj/Developer/Work/Selina/SelinaCore/node_modules/luxon/build/cjs/luxon.js:7718:19)
    at DateTime.get$$1 (/Users/aj/Developer/Work/Selina/SelinaCore/node_modules/luxon/build/cjs/luxon.js:7718:19)
    at DateTime.get$$1 (/Users/aj/Developer/Work/Selina/SelinaCore/node_modules/luxon/build/cjs/luxon.js:7718:19)
    at DateTime.get$$1 (/Users/aj/Developer/Work/Selina/SelinaCore/node_modules/luxon/build/cjs/luxon.js:7718:19)
    at DateTime.get$$1 (/Users/aj/Developer/Work/Selina/SelinaCore/node_modules/luxon/build/cjs/luxon.js:7718:19)
    at DateTime.get$$1 (/Users/aj/Developer/Work/Selina/SelinaCore/node_modules/luxon/build/cjs/luxon.js:7718:19)
```

I have not found a way to reproduce the error in an isolated environment or test.

Luxon 0.0.19
Node 8.9.1

**Comment by icambron** [comment]
That's an odd one. I have a couple of guesses, but it would be easier for me if you tried the latest Luxon and gave me the stacktrace from that

**Comment by alewaros** [comment]
Hi @icambron, the latest version fixed it, thanks for the tip and sorry for not checking throughly. ✌️

**Comment by icambron** [comment]
Sweet

**Comment by OzzieOrca** [comment]
For anyone else who might search for this error, don't call a Luxon function inside the [`Settings.now`](https://moment.github.io/luxon/docs/class/src/settings.js~Settings.html#static-set-now) function. It seems to create an infinite loop of creating a `DateTime`, needing the `Settings.now` date, and trying to get it but creating another `DateTime` which calls the `Settings.now` function again.

Use
```ts
Settings.now = () => new Date(2020, 1, 1).valueOf();
```
instead of
```ts
Settings.now = () => DateTime.local(2020, 2, 1).valueOf(); // throws Maximum call stack size exceeded error
```

https://github.com/moment/luxon/issues/254#issuecomment-386495652 is a good thread about testing.
