### ISSUE TITLE
Conflict  with vue3.3.4

### ISSUE THREAD

**Issue by HamasakiBrain** [moment/luxon#1522]
Hello, luxon conflict with vue 3.3.4

0 verbose cli /Users/user/.nvm/versions/node/v20.2.0/bin/node /Users///.nvm/versions/node/v20.2.0/bin/npm
1 info using npm@9.7.1
2 info using node@v20.2.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users///.nvm/versions/node/v20.2.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/plove/Desktop/Projects/Adwos/admin-nuxt/.npmrc Completed in 1ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/Users/plove/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/Users/plove/.nvm/versions/node/v20.2.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 10ms
17 timing npm:load:configload Completed in 10ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install luxon
22 verbose argv "install" "--save" "luxon"
23 timing npm:load:setTitle Completed in 9ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/Users/plove/.npm/_logs/2023-10-07T22_16_00_981Z-
26 verbose logfile /Users/plove/.npm/_logs/2023-10-07T22_16_00_981Z-debug-0.log
27 timing npm:load:logFile Completed in 8ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 40ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 2 files
33 timing command:install Completed in 14ms
34 verbose stack Error: Override for vue@^3.3.4 conflicts with direct dependency
34 verbose stack     at Node.assertRootOverrides (/Users/plove/.nvm/versions/node/v20.2.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1334:29)
34 verbose stack     at #loadActual (/Users/plove/.nvm/versions/node/v20.2.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-actual.js:135:24)
34 verbose stack     at async Promise.all (index 0)
34 verbose stack     at async Arborist.reify (/Users/plove/.nvm/versions/node/v20.2.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
34 verbose stack     at async Install.exec (/Users/plove/.nvm/versions/node/v20.2.0/lib/node_modules/npm/lib/commands/install.js:148:5)
34 verbose stack     at async module.exports (/Users/plove/.nvm/versions/node/v20.2.0/lib/node_modules/npm/lib/cli-entry.js:61:5)
35 verbose cwd /Users/plove/Desktop/Projects/Adwos/admin-nuxt
36 verbose Darwin 23.0.0
37 verbose node v20.2.0
38 verbose npm  v9.7.1
39 error code EOVERRIDE
40 error Override for vue@^3.3.4 conflicts with direct dependency
41 verbose exit 1
42 timing npm Completed in 206ms
43 verbose unfinished npm timer reify 1696716961178
44 verbose unfinished npm timer reify:loadTrees 1696716961181
45 verbose unfinished npm timer idealTree 1696716961181
46 verbose unfinished npm timer idealTree:init 1696716961182
47 verbose code 1
48 error A complete log of this run can be found in: /Users/plove/.npm/_logs/2023-10-07T22_16_00_981Z-debug-0.log

npm ERR! code EOVERRIDE
npm ERR! Override for vue@^3.3.4 conflicts with direct dependency

**Comment by HamasakiBrain** [comment]
My package.json
```
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxt/ui": "^2.9.0",
    "@pinia/nuxt": "^0.4.11",
    "nuxt": "^3.7.4",
    "sass": "^1.69.0",
    "vue": "^3.3.4",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@headlessui/vue": "^1.7.16",
    "@heroicons/vue": "^2.0.18",
    "pinia": "^2.1.6"
  },
  "overrides": {
    "vue": "latest"
  }
}

```
