### ISSUE TITLE
DateTime.fromFormat throws exception if used with IANA time zones

### ISSUE THREAD

**Issue by DanielSWolf** [moment/luxon#408]
The `DateTime` methods `toFormat()` and `fromFormat` are symmetric. That is, I can use `toFormat()` to convert a `DateTime` to a string value; then I can use the same format string to read the string value back into a `DateTime`.

That works well for most time-zone formats from [the documented table of tokens](https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens). But when using `z` for IANA zones, `fromFormat()` throws an exception.

Here's a demo:

```js
const { DateTime } = require('luxon');

const d = DateTime.fromObject({ year: 2019, month: 01, day: 14, hour: 11, minute: 30, zone: 'Indian/Maldives' });

const shortOffsetFormat = "yyyy-MM-dd'T'HH-mmZZ";
// 🙂 Prints "2019-01-14T11-30+05:00"
console.log(d.toFormat(shortOffsetFormat));
// 🙂 Prints 5
console.log(DateTime.fromFormat('2019-01-14T11-30+05:00', shortOffsetFormat, { setZone: true }).zone.offset(d) / 60);

const ianaFormat = "yyyy-MM-dd'T'HH-mm[z]";
// 🙂 Prints "2019-01-14T11-30[Indian/Maldives]"
console.log(d.toFormat(ianaFormat));
// 😥 Should print "Indian/Maldives", but throws exception "Invalid regular expression: /[/: Unterminated character class"
console.log(DateTime.fromFormat('2019-01-14T11-30[Indian/Maldives]', ianaFormat, { setZone: true }).zoneName);
```

Here is the full exception:

```text
SyntaxError: Invalid regular expression: /[/: Unterminated character class
    at RegExp (<anonymous>)
    at literal (/Users/wolf/dev/luxon-test/node_modules/luxon/build/node/luxon.js:4081:12)
    at unitate (/Users/wolf/dev/luxon-test/node_modules/luxon/build/node/luxon.js:4087:14)
    at unitForToken (/Users/wolf/dev/luxon-test/node_modules/luxon/build/node/luxon.js:4240:16)
    at tokens.map.t (/Users/wolf/dev/luxon-test/node_modules/luxon/build/node/luxon.js:4366:33)
    at Array.map (<anonymous>)
    at explainFromTokens (/Users/wolf/dev/luxon-test/node_modules/luxon/build/node/luxon.js:4366:24)
    at parseFromTokens (/Users/wolf/dev/luxon-test/node_modules/luxon/build/node/luxon.js:4396:7)
    at Function.fromFormat (/Users/wolf/dev/luxon-test/node_modules/luxon/build/node/luxon.js:5290:41)
    at Object.<anonymous> (/Users/wolf/dev/luxon-test/index.js:15:22)
```

**Comment by icambron** [comment]
Fixed in #432
