### ISSUE TITLE
Invalid assignment error from uglify-js

### ISSUE THREAD

**Issue by sherryxiao1988** [moment/luxon#467]
Hi all,

I am using luxon inside the [tarojs](https://github.com/NervJS/taro) framework. `npm run dev` seems working fine but when I build this project, i got the following error:

```
Compression error Users/sxiao/workspace/gem-frontend/node_modules/luxon/build/node/luxon.js
{ SyntaxError: Invalid assignment
    at JS_Parse_Error.get (eval at <anonymous> (/Users/sxiao/workspace/gem-frontend/node_modules/uglify-js/tools/node.js:20:1), <anonymous>:71:23)
    at formatError (internal/util/inspect.js:869:16)
    at formatRaw (internal/util/inspect.js:654:14)
    at formatValue (internal/util/inspect.js:545:10)
    at inspect (internal/util/inspect.js:196:10)
    at Object.formatWithOptions (util.js:84:12)
    at Console.(anonymous function) (internal/console/constructor.js:274:15)
    at Console.log (internal/console/constructor.js:283:59)
    at recursiveRequire (/Users/sxiao/.nvm/versions/node/v11.7.0/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:210:19)
    at resolveNpmFilesPath (/Users/sxiao/.nvm/versions/node/v11.7.0/lib/node_modules/@tarojs/cli/src/util/resolve_npm_files.js:72:5)
  message: 'Invalid assignment',
  filename: '0',
  line: 46,
  col: 33,
  pos: 1177 }
```

My node version is 11.7.0 and my luxon version is 1.11.4.

Can anyone help on this?
Thanks a lot!

**Comment by icambron** [comment]
Uglify-JS only supports ECMAScript 5. Luxon is written in EMCAScript2018 and compiled for different environments, and thus each build reflects the level of modern JS support those environments have. Luxon's Node build (the "main" file in the NPM package) targets Node 6, which supports a lot of newer syntax, and I suspect Uglify is choking on it. I think you probably want to point at the `cjs-browser` build of Luxon (also in the NPM package), which targets older browsers and should be compatible with Uglify.

I hope that helps!

**Comment by sherryxiao1988** [comment]
@icambron thanks a lot for the detailed explanation! My problem is solved :)
