### ISSUE TITLE
offsetNameLong and offsetNameShort break in the absence of Intl support

### ISSUE THREAD

**Issue by icambron** [moment/luxon#47]
```js
> DateTime.local().offsetNameShort
'EDT'
> Intl = null
null
> DateTime.local().offsetNameShort
TypeError: Cannot read property 'DateTimeFormat' of null
    at Function.parseZoneInfo (/Users/isaac/code/luxon/build/cjs/luxon.js:2897:15)
    at LocalZone.offsetName (/Users/isaac/code/luxon/build/cjs/luxon.js:2464:19)
    at DateTime.get$$1 (/Users/isaac/code/luxon/build/cjs/luxon.js:7360:26)
    at repl:1:17
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:120:20)
```

**Comment by icambron** [comment]
Fixed in 043fef1
