### ISSUE TITLE
Not working with ESM on Node v13.5.0

### ISSUE THREAD

**Issue by jeremiahlee** [moment/luxon#639]
I am trying to use Luxon with Node v13.5.0. I am getting this error:

```
(node:61162) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/jeremiah/Projects/test-project/index.js:1
import { DateTime } from "luxon";
         ^^^^^^^^
SyntaxError: The requested module 'luxon' does not provide an export named 'DateTime'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:141:24)
```

I created a quick demo of this problem.

index.js:
```
import { DateTime } from "luxon";
```

package.json:
```
{
  "name": "test-project",
  "main": "index.js",
  "type": "module",
  "dependencies": {
    "luxon": "^1.21.3"
  }
}
```

**Comment by icambron** [comment]
Please see #252. I think we just need to create an ESM build target
