### ISSUE TITLE
dateTime.setZone('UTC').toFormat('ff') is failing (RangeError)

### ISSUE THREAD

**Issue by NicolasGripont** [moment/luxon#883]
**Describe the bug**
Calling the method `toFormat` after setting the time zone to `UTC` is failing with `v1.26.0`. It was working with the previous version.
**To Reproduce**
```js
const {DateTime} = require('luxon');
console.log(DateTime.fromISO('2021-02-18T23:59:59.999Z').setZone('UTC').toFormat('ff'));
```
**Actual vs Expected behavior**
- With version 1.25.0: we are getting the following log:
```
Feb 18, 2021, 11:59 PM
```
- With version 1.26.0: we are getting the following error
```
/Users/nicolas/Gitlab/test/node_modules/luxon/build/node/luxon.js:1944
    dtf = new Intl.DateTimeFormat(locString, opts);
          ^

RangeError: Expected Area/Location(/Location)* for time zone, got Etc/GMT+0
    at new DateTimeFormat (native)
    at getCachedDTF (/Users/nicolas/Gitlab/test/node_modules/luxon/build/node/luxon.js:1944:11)
    at new PolyDateFormatter (/Users/nicolas/Gitlab/test/node_modules/luxon/build/node/luxon.js:2173:18)
    at Locale.dtFormatter (/Users/nicolas/Gitlab/test/node_modules/luxon/build/node/luxon.js:2423:12)
    at Formatter.formatWithSystemDefault (/Users/nicolas/Gitlab/test/node_modules/luxon/build/node/luxon.js:798:31)
    at maybeMacro (/Users/nicolas/Gitlab/test/node_modules/luxon/build/node/luxon.js:864:21)
    at tokenToString (/Users/nicolas/Gitlab/test/node_modules/luxon/build/node/luxon.js:1123:18)
    at stringifyTokens (/Users/nicolas/Gitlab/test/node_modules/luxon/build/node/luxon.js:698:12)
    at Formatter.formatDateTimeFromString (/Users/nicolas/Gitlab/test/node_modules/luxon/build/node/luxon.js:1127:12)
    at DateTime.toFormat (/Users/nicolas/Gitlab/test/node_modules/luxon/build/node/luxon.js:6764:74)
```
**Desktop (please complete the following information):**

- OS: OSX 11.2.1
- luxon: 1.26.0 vs 1.25.0
- node: v10.20.1
- npm: 6.13.4
**Additional context**

**Comment by icambron** [comment]
This is probably caused by #867. We may have to roll that back until Node catches up.

**Comment by circlingthesun** [comment]
Please do roll this back. We got nailed by this today. Here are some affected browsers from our error logs:

61.07%	Samsung Internet 12.0
21.48%	Firefox 78.0
6.04%	Mobile Safari 13.0.5
5.37%	Chrome Mobile 77.0.3865
4.03%	Mobile Safari 14.0.3
1.34%	Chrome 56.0.2924
0.67%	Samsung Internet 13.2

**Comment by durasj** [comment]
Although I'm not impacted, I would hate to see this being rolled back as Luxon would lose support for the formatting of fixed offset timezones. So I've opened #918 that should fix this.
